### ISSUE TITLE
Nothing displayed after startup screen.

### ISSUE THREAD

**Issue by limbo666** [eeyrw/LcdTcp#3]
> That sounds weired. "standby Ip address" indicates that the device has been successfully connected to Wi-Fi and display is working. It should work if you configure LCD-Smartie with versus DLL driver (https://github.com/eeyrw/LcdTcpDll) correctly.

I have the same problem . 
It seems that data are arriving correctly to the firmware but the display stays on last startup messages which is IP address. 
I have checked by adding a    `Serial.print( char(Buf[2+i]) ); ` on 
`CMD_LCD_WRITEDATA `  and I can confirm that connection between LCD Smartie and hardware is correct. the serial monitor displays exactly the data LCD Smaries sends, however the LCD doesn't change.
Any ideas?

_Originally posted by @limbo666 in https://github.com/eeyrw/LcdTcp/issues/2#issuecomment-1117948097_

**Comment by eeyrw** [comment]
I have no hardware in hand for debugging. So I just make some guess. Did you set the correct LCD size in LCD Smartie? Because the LCD will be re-initialized after LCD Smartie getting control:
https://github.com/eeyrw/LcdTcp/blob/f960ef97238f222b6113fb64ce1e7e3aa83c04db/CmdProc.cpp#L46

**Comment by minolmal** [comment]
I used a WEMOS D1 mini + I2C LCD display(display is an oled character display, but work fine. hangs with garbage characters  sometimes, nibble sync and proper wiring should fix it).

I generally prefer PlatformIO, So I ported LcdTcp sources. First I used LiquidCrystal_I2C library from library manager. It broke the code. So I used included the edited library in original source. found few glitches. but since my purposes don't clash with those glitches, I simply used what is working. (eg: left-> right transition flips the string)
latest LCD smartie 5.4.2.92++ along with LcdTcp releases worked fine for me.

I wanted to use Sensor Bridge plugin, for some reason forum register confirmation email is late. so I can't download it. used aida.dll and all work fine so far.

**Comment by limbo666** [comment]
> I have no hardware in hand for debugging. So I just make some guess. Did you set the correct LCD size in LCD Smartie? Because the LCD will be re-initialized after LCD Smartie getting control:
> 
> https://github.com/eeyrw/LcdTcp/blob/f960ef97238f222b6113fb64ce1e7e3aa83c04db/CmdProc.cpp#L46

You pointed to the correct direction.
The ```CMD_LCD_INIT``` requires the correct address of the I2C module. In my case was ```0x27``` and the source code has ```0x3c```.
I overlooked this since I thought this is should me replaced only in ```LCDInterface.cpp``` file.

Changing the address in the ```CMD_LCD_INIT``` to the correct one does the trick.
Thank you for your support. :+1:
